alter table reflections
add column if not exists emotional_validation text,
add column if not exists emotion text,
add column if not exists trigger text,
add column if not exists facts text,
add column if not exists interpretation text,
add column if not exists thought_pattern text,
add column if not exists behaviour text,
add column if not exists body_factor text,
add column if not exists behavioural_insight text,
add column if not exists next_question text,
add column if not exists next_step text,
add column if not exists next_step_type text,
add column if not exists mode text,
add column if not exists mode_detected text,
add column if not exists language text,
add column if not exists follow_up_result text,
add column if not exists follow_up_note text,
add column if not exists follow_up_at timestamp with time zone;
